//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CXCommenter: 0.9.5.0.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="CXCommenterPackage.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
global using Community.VisualStudio.Toolkit;
global using Microsoft.VisualStudio.Shell;
global using System;
global using Task = System.Threading.Tasks.Task;
using System.Runtime.InteropServices;
using System.Threading;

/// <summary>
///       Namespace Name - CXCommenter.
/// </summary>
namespace CXCommenter
{
    [PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
    [InstalledProductRegistration(Vsix.Name, Vsix.Description, Vsix.Version)]
    [ProvideMenuResource("Menus.ctmenu", 1)]
    [Guid(PackageGuids.CXCommenterString)]
    public sealed class CXCommenterPackage : ToolkitPackage
    {

        /// <summary>
        ///     Function Name - InitializeAsync.
        /// </summary>
        /// <param name="System.Threading.CancellationToken cancellationToken">: Describe System.Threading.CancellationToken cancellationToken here.</param>
        /// <param name="System.IProgress<Microsoft.VisualStudio.Shell.ServiceProgressData> progress">: Describe System.IProgress<Microsoft.VisualStudio.Shell.ServiceProgressData> progress here.</param>
        /// <returns>System.Threading.Tasks.Task.</returns>
        protected override async Task InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)
        {
            await this.RegisterCommandsAsync();
        }
    }
}