// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CXCommenter
{
    internal sealed partial class Vsix
    {
        public const string Id = "CXCommenter.55051f0e-32a9-4a22-932f-1602de247f6b";
        public const string Name = "CXCommenter";
        public const string Description = @"An  automatic Comment Generating Tool For Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "XML-commenter, Documentation-Generator, XML-Comments,Productivity-Enhancement,Code-Insights";
    }
}
